version: "3"
services:
  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-Remote
    restart: on-failure
    ports:
      - "8888:80"
    volumes:
      - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      PMA_HOST: "${PMA_HOST}"
